server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server:8761/eureka"
spring:
  application:
    name: "inst-post-service"
  datasource:
    url: "jdbc:postgresql://postgres-post:5432/post"
    username: "postgres"
    password: "1234"
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    loadbalancer:
      enabled: false


keycloak:
  auth-server-url: http://auth-service:8080/auth
  realm: inst-project
  resource: inst-post-service
  ssl-required: external
  bearer-only: true
  use-resource-role-mappings: true
  credentials:
    secret: k3btbbCJUOHYognirHGiHgFzYU73rwkC