server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: inst-post-service
  datasource:
    url: jdbc:postgresql://postgres-post:5432/post
    username: postgres
    password: 1234
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    loadbalancer:
      enabled: false


keycloak:
  realm: inst-project
  auth-server-url: http://keycloak:8080/auth/
#  auth-server-url: "http://localhost:8484/auth/"
  ssl-required: "external"
  resource: "inst-post-service"
  use-resource-role-mappings: true
  bearer-only: true
#  verify-token-audience: true



#security:
#  oauth2:
#    resource:
#      id: inst-post-service
#      token-info-uri: http://localhost:8080/auth/realms/inst-project/protocol/openid-connect/token/introspect
#      user-info-uri: http://localhost:8080/auth/realms/inst-project/protocol/openid-connect/userinfo
#      jwt:

#        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgCZ/HTarAWtGi/I3P9LA4TKWMtHxSxtNmKc/sqYJFHHUduMVDmYHsIW7Vhg7lulmSWQVwEaKNLswKUyeHZvzJqob1Gv4itsJWVHOPHux5j1W4/SsOXVMiYicIL29macZwxSPDxn16NczAmRZ8lE2WNOnGZKr+EJeTqkQZ01VcNwbxsbMWomfNhYLNsppz4YY7gQ5swaxwNbeAc1f9WWc0t+YGR/gE8dFSoAlvoMZNXwzYHGeHJI9anluLF8nzEmjB8cIQSzLluup6cUA/QfC5Ek8MS4tZ8Kdu0bk9BIS1D4+tOkE35gHJYPgVFywLOwC12aJ/sruOsyQcYLz9YDzFwIDAQAB